"""
THIS FILE WILL EVENTUALLY CONTAIN THE LIBRARY OF BLACKJACK.
I WILL BE TAKING THE BLACKJACK GAME I CREATED IN A PREVIOUS
PROJECT AND ALTERING IT SLIGHTLY TO BE USED IN THE 
HANDTRACKINGGAME.PY FILE.
"""